encyclopedia/urls.py
from django.urls import path

from . import views

# Uniquely Identify Routes for Wiki
app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("encyclopedia.urls", 'encyclopedia'), namespace='encyclopedia'))
    
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.urls import reverse
from django.shortcuts import render
from . import util
from django.http import HttpResponseRedirect
from django import forms
from random import randint


# Importing the Markdown Entries so that we can retrieve them
import markdown2

# Create a new Class for Django Form
class CreateWikiForm(forms.Form):
    # Create 2 Input Fields for Name and Details
    wiki_name = forms.CharField(label="Name of New Wiki Page:")
    wiki_details = forms.CharField(
        label="Details about the New Wiki Page:", 
        # Setting Size of Textarea
        widget=forms.Textarea(
            attrs={ 'rows': 20,
                    'cols': 60,
                    'style': 'height: 50vh; display: block;'})
        )

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Creating a Route for the Entry Page
def entry(request, title):
    # Return the Markdown Content from the Page Requested
    requested_md = util.get_entry(title)
    # Validation to Ensure Markdown is not Empty
    if (requested_md == None):
        # Entry does not exist; Render an Error Page
        return render(request, "encyclopedia/error.html")
    
    # Convert the Markdown files into HTML
    markdowner = markdown2.Markdown()
    html_content = markdowner.convert(requested_md)

    return render(request, "encyclopedia/entry.html", {
        # Passing in Key-Value Pairs for Context
        "title" : title,
        "content" : html_content
    })

# Search Functionality
def search(request):
    # Get User Input
    query = request.GET['q']
    # Check if User's Query Terms is an Existing Page
    existing_entries = util.list_entries()
    if query in existing_entries:
        # If it is, determine the title the entry page
        queried_md = util.get_entry(query)
        if (queried_md == None):
            return render(request, "encyclopedia/error.html")
        # Redirect the User to the page they searched for
        else:
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[query]))
    
    # If the Query is not an Existing Page
    else:
        # List to hold related entries
        related_entries = []
        # Make the Query a Substring
        sub_string = str(query)
        # Check if Substring is part of the List of Entries (Strings) and add it to an empty list
        results = [substr for substr in existing_entries if sub_string in substr]
        # Append to our List of Related Entries
        related_entries += results
        # After Looping through all the available titles        
        return render(request, "encyclopedia/search.html", {
            "titles" : related_entries
        })

# Create a New Wiki Page
def create(request):
    if request.method == "POST":
        # Get Form Data from User, Key is referenced from the name of variables when we create the Class
        wiki_title = request.POST["wiki_name"]
        wiki_details = request.POST["wiki_details"]
        # Check if Created Page is Existing
        existing_entries = util.list_entries()
        if wiki_title in existing_entries:
            # Return an Error Message as Page is existing
            return render(request, "encyclopedia/create_error.html")
        
        # If Wiki Page is a New Page
        else:
            # Save New Wiki Page
            util.save_entry(wiki_title, wiki_details)
            # Redirect User to Newly Created Page
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[wiki_title]))


    
    # If User wants to go to Form Page
    else:
        # Return the Render of the Create HTML
        return render(request, "encyclopedia/create.html",{
            # But Pass in the Django Form we created
            "create_form": CreateWikiForm()
        })

# Editing an existing Wiki Page
def edit(request, title):
    if request.method == "POST":
        # Get User Input to Save
        wiki_details = request.POST["wiki_details"]

        # Save the Edits to the Page
        util.save_entry(title, wiki_details)
        # Redirect User to the edited page
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]  ))

    # GET Request to go to Edit Page
    else:
        # Get Markdown of the Page
        name = title
        markdown_files = util.get_entry(title)
        # Provide Initial Values for Existing Wiki Page
        existing_form = CreateWikiForm(initial={
            'wiki_name': title,
            'wiki_details': markdown_files
        })
        # Render the Template, Passing in our Form Data
        return render(request, "encyclopedia/edit.html", {
            'form': existing_form,
            'name': name
        })

# Providing the User with a Random Wiki Page
def random(request):
    # Get List of Entries
    existing_entries = util.list_entries()
    list_size = len(existing_entries)
    # Randomly Select one of the Existing Entries
    rand_index = randint(0, (list_size - 1))
    # Render the Selected Page
    selected_title = existing_entries[rand_index]
    selected_markdown = util.get_entry(selected_title)
    html = markdown2.markdown(selected_markdown)
    return render(request, "encyclopedia/entry.html", {
        'title': selected_title,
        'content': html
    })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create New Page
{% endblock %}

{% block body %}
    <h1> Create a New Page for the Wiki </h1>
    <!-- Form for User to Submit Page Name and Page Details -->
    <form action="{% url 'encyclopedia:create' %}" class="form_fields" method="post">
        <!-- CSRF Token to prevent Hacking -->
        {% csrf_token %}
        <!-- Substituting with the Django Class I created instead of manually writing everything down -->
        <div name="create_form_title" class="form_fields">
            <!-- New Wiki Page's Name -->
            {{ create_form.wiki_name.label }}
        </div>
        <div class="form_fields">
            {{ create_form.wiki_name }}
        </div>
        <div name="create_form_details" class="form_fields">
            <!-- New Wiki Page's Details -->
            {{ create_form.wiki_details.label }}
            {{ create_form.wiki_details }}
        </div>
        <div class="form_fields">
            <!-- Button to Submit -->
            <button class="btn btn-secondary" style="margin-top: 1%;" type="submit">Submit</button>
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/create_error.html
{% extends "encyclopedia/layout.html" %}

{% block title%}
New Wiki Page Error
{% endblock %}

{% block body %}
    <h3> You are not allowed to create this Wiki Page because this page is already existing!!</h3>

    <h4>Possible Actions: </h4>
    <h6>1. Edit the existing page.</h6>
    <h6>2. Click <a href="/">here</a> to go back to the Homepage!!!</h6>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit Wiki Entry
{% endblock %}

{% block body %}
    <h1>Edit this Wiki Page</h1>
    <!-- Using Reverse Function to send to Edit not Entry!!! and Pass in the Wiki Name as the Title for the URL -->
    <!-- If I had sent to Entry, the changes won't be saved. By sending to Edit, I am then redirected to Entry -->
    <form method="POST" action="{% url 'encyclopedia:edit' name %}" class="form_fields">
        <!-- CSRF Token to prevent Hacking -->
        {% csrf_token %}
        <!-- 2 Input Fields with Existing Data Filled in -->
        <div class="form_fields">
            {{ form.wiki_name.label }}
            <h4>{{ name }}</h4>
        </div>
        <div class="form_fields">
            {{ form.wiki_details.label }}
            {{ form.wiki_details }}
        </div>
        <div>
            <!-- Empty Space-->
        </div>
        <div class="submit-button" style="margin-top: 1%;">
            <button class="btn btn-secondary" type="submit">Submit Changes</button>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title%}
{{ title }}
{% endblock %}

{% block body %}
    <!-- Add an Edit Button -->
    <div>
        <!-- Since my Edit Function needs a 2nd argument title, I need to provide it in the URL somehow -->
        <a role="button" class="btn btn-secondary" href="{% url 'encyclopedia:edit' title %}">Edit</a>
        <!-- <input type="hidden" value="{{ title }}"> -->
    </div>
    <div>
        {{ content | safe }}
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title%}
Error
{% endblock %}

{% block body %}
    <h1>Sorry, this page does not exists!!</h1>
    <h6>Click <a href="/">here</a> to go back to the Homepage!!!</h6>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
<!-- To include the CSS and SASS Files in our Static Folder -->
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- Including Bootstrap and our own CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body style="overflow:hidden;">
        <!-- Vertical Nav Bar on the Left -->
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <!-- Search Field -->
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search
{% endblock %}

{% block body %}
    <h1>Sorry, the page you're looking for does not exists!!!</h1>
    <h5>Here are some related entries:</h5>

    <!-- For Loop to Loop through Entries that are a substring -->
    <ul>
        {% for title in titles %}
        <li><a href="/wiki/{{ title }}">{{ title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}